global:
  scrape_interval: 500ms
  evaluation_interval: 500ms

scrape_configs:
  - job_name: "op-node"
    static_configs:
      - targets: ["host.docker.internal:7300"]
    metrics_path: /metrics
  - job_name: "builder-op-geth"
    static_configs:
      - targets: ["host.docker.internal:6063"]
    metrics_path: /debug/metrics/prometheus
