{
 "title": "L2 Builder",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Miner Block Build Duration (Quartile)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miner_block_build{quantile=\"0.5\"} or\nminer_block_build{quantile=\"0.75\"} or\nminer_block_build{quantile=\"0.95\"} or\nminer_block_build{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custom GetPayload Duration (Quartile)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "builder_duration_getPayload_success{quantile=\"0.5\"} or\nbuilder_duration_getPayload_success{quantile=\"0.75\"} or\nbuilder_duration_getPayload_success{quantile=\"0.95\"} or\nbuilder_duration_getPayload_success{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_block_gasused", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All RPC Response Duration (Quantile)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_duration_all{quantile=\"0.5\"} or\nrpc_duration_all{quantile=\"0.75\"} or\nrpc_duration_all{quantile=\"0.95\"} or\nrpc_duration_all{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Block Build Duration (Quantile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "miner_block_build{quantile=\"0.5\"} or\nminer_block_build{quantile=\"0.75\"} or\nminer_block_build{quantile=\"0.95\"} or\nminer_block_build{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Build Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(miner_block_build_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size (Gas)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "miner_block_gasused", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Custom Get Payload Response Duration (Quantile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "builder_duration_getPayload_success{quantile=\"0.5\"} or\nbuilder_duration_getPayload_success{quantile=\"0.75\"} or\nbuilder_duration_getPayload_success{quantile=\"0.95\"} or\nbuilder_duration_getPayload_success{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custom Get Payload Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(builder_duration_getPayload_success_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(builder_duration_getPayload_failure_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "All RPC Response Duration (Quantile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rpc_duration_all{quantile=\"0.5\"} or\nrpc_duration_all{quantile=\"0.75\"} or\nrpc_duration_all{quantile=\"0.95\"} or\nrpc_duration_all{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All RPC Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_success[$__rate_interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(rpc_failure[$__rate_interval])",
     "legendFormat": "failure"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "avg(system_cpu_sysload)", "legendFormat": "system" },
    { "expr": "avg(system_cpu_syswait)", "legendFormat": "iowait" },
    { "expr": "avg(system_cpu_procload)", "legendFormat": "geth" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_memory_used", "legendFormat": "used" }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  }
 ]
}